# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swipe',
            name='swipe_type',
            field=models.CharField(choices=[('IN', 'Login'), ('OUT', 'Logout'), ('OBR', 'On Break'), ('FBR', 'From Break')], max_length=3),
        ),
    ]
