# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-24 11:05
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(max_length=20)),
                ('hours_quota', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(8), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_since', models.DateField(default=None)),
                ('date_to', models.DateField(default=None)),
                ('work_hours', models.FloatField(default=0)),
                ('verified', models.BooleanField(default=False)),
                ('reason', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('key_type', models.CharField(blank=True, max_length=4, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aviable_holidays', models.FloatField(default=0, verbose_name='Already aviable holidays in hours')),
                ('days_of_holidays_per_year', models.IntegerField(default=20)),
                ('contracts', models.ManyToManyField(to='attendance.Contract')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('private', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSeparation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('time_spend', models.DurationField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Project')),
            ],
        ),
        migrations.RemoveField(
            model_name='session',
            name='description',
        ),
        migrations.AddField(
            model_name='swipe',
            name='correction_of_swipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.Swipe'),
        ),
        migrations.AddField(
            model_name='swipe',
            name='source',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='swipe',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.Session'),
        ),
        migrations.AlterField(
            model_name='swipe',
            name='swipe_type',
            field=models.CharField(choices=[('IN', 'Login'), ('OUT', 'Logout'), ('OBR', 'On Break'), ('FBR', 'From Break'), ('OTR', 'On Trip'), ('FTR', 'From Trip')], max_length=3),
        ),
        migrations.AddField(
            model_name='projectseparation',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Session'),
        ),
        migrations.AddField(
            model_name='holiday',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='attendance.Profile'),
        ),
        migrations.AddField(
            model_name='session',
            name='project',
            field=models.ManyToManyField(through='attendance.ProjectSeparation', to='attendance.Project'),
        ),
    ]
