# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 21:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20160411_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swipe',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.Session'),
        ),
    ]
