# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 21:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20160412_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swipe',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.Session'),
        ),
    ]
