# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_auto_20160416_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swipe',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.Session'),
        ),
    ]
