# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_auto_20160417_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swipe',
            name='swipe_type',
            field=models.CharField(choices=[('IN', 'Login'), ('OUT', 'Logout'), ('OBR', 'On Break'), ('FBR', 'From Break'), ('OTR', 'On Trip'), ('FTR', 'From Trip')], max_length=3),
        ),
    ]
