# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 18:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_usermethods'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserMethods',
        ),
    ]
