# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_auto_20160531_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
