# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_project_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='swipe',
            name='corrected_swipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.Swipe'),
        ),
    ]
