# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 21:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_auto_20160531_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='swipe',
            old_name='correcting',
            new_name='correction',
        ),
    ]
