# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 21:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_auto_20160531_2134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='swipe',
            old_name='correct_swipe',
            new_name='correction_of_swipe',
        ),
        migrations.RemoveField(
            model_name='swipe',
            name='correction',
        ),
    ]
