# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0017_auto_20160531_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='description',
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projectseparation',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
