# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-14 09:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0020_contract_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='contract',
            new_name='contracts',
        ),
    ]
