# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-19 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0022_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(max_length=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='haveHolidays',
        ),
        migrations.AddField(
            model_name='profile',
            name='have_holidays',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='contract',
            field=models.ManyToManyField(to='attendance.Contract'),
        ),
    ]
