# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-19 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0023_auto_20170619_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='have_holidays',
        ),
    ]
