# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-19 14:50
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0024_remove_profile_have_holidays'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='hours_quota',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(8), django.core.validators.MinValueValidator(0)]),
        ),
    ]
