# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-19 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0025_contract_hours_quota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(max_length=20),
        ),
    ]
