# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-26 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0027_auto_20170621_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holiday',
            name='user',
        ),
        migrations.AddField(
            model_name='holiday',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='attendance.Profile'),
            preserve_default=False,
        ),
    ]
