# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-26 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0029_auto_20170626_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='profile',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='attendance.Profile'),
        ),
    ]
