# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-26 10:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0032_auto_20170626_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holiday',
            name='time_spend',
        ),
        migrations.AddField(
            model_name='holiday',
            name='days_spend',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
