# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-26 10:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0033_auto_20170626_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='days_spend',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.5)]),
        ),
    ]
