# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-27 10:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0035_profile_aviable_holidays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='attendance.Profile'),
        ),
    ]
