# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-29 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0037_auto_20170629_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_time_year',
            field=models.IntegerField(default=2017),
        ),
    ]
