# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-29 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0038_profile_last_time_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holiday',
            old_name='date',
            new_name='date_since',
        ),
        migrations.AddField(
            model_name='holiday',
            name='date_to',
            field=models.DateField(default=None),
        ),
    ]
