# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-29 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0040_auto_20170629_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='date_to',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
