# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-03 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0042_auto_20170629_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='reason',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='weeks_of_holidays_per_year',
            field=models.IntegerField(default=0),
        ),
    ]
