# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-10 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0043_auto_20170703_0826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holiday',
            old_name='hours_spend',
            new_name='work_hours',
        ),
        migrations.AlterField(
            model_name='holiday',
            name='reason',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
