# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-10 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0044_auto_20170710_0820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holiday',
            name='work_hours',
        ),
        migrations.AddField(
            model_name='holiday',
            name='days_on_holidays',
            field=models.FloatField(default=0),
        ),
    ]
