# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-10 11:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0045_auto_20170710_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holiday',
            old_name='days_on_holidays',
            new_name='hours_on_holidays',
        ),
    ]
