# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-12 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0046_auto_20170710_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_time_year',
        ),
        migrations.AddField(
            model_name='profile',
            name='last_action_time',
            field=models.DateTimeField(default=None),
        ),
    ]
