# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-19 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0049_auto_20170712_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_action_time',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='weeks_of_holidays_per_year',
        ),
        migrations.AddField(
            model_name='profile',
            name='days_of_holidays_per_year',
            field=models.IntegerField(default=20),
        ),
    ]
