# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-14 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0049_auto_20170714_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='aviable_holidays',
            field=models.FloatField(default=0, verbose_name='Already aviable holideys in hours'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_action_time',
            field=models.DateTimeField(default=None),
        ),
    ]
